version: 38
jobs:
- name: nestjs-backend
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunImagetoolsStep
    name: run buildx
    arguments: --target=teable --IMAGE_REGISTRY=git.dev.aerok.com.cn/aes-digital-project/teable
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
